# docker/Dockerfile.write-service

# Use the official Node.js image as the base image
FROM node:20-alpine

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY ./server/apps/write-service/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY ./server/apps/write-service .

# Expose the port the app runs on
EXPOSE 3000

# Start the NestJS application with hot reload
CMD ["npm", "run", "start:dev"]